apiVersion: apps/v1
kind: Deployment
metadata:
  name: reddit-bot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: reddit-bot
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: reddit-bot
    spec:
      containers:
      - name: reddit-bot
        image: gcr.io/PROJECT_ID/IMAGE:TAG
        ports:
        - containerPort: 5000
        env:
          - name: PRAW_CLIENT_ID
            value: ${{secrets.PRAW_CLIENT_ID}}
          - name: PRAW_CLIENT_SECRET
            value: PRAW_CLIENT_SECRET
          - name: PRAW_PASSWORD
            value: PRAW_PASSWORD
          - name: PRAW_USER_AGENT
            value: PRAW_USER_AGENT
        resources:
          requests:
            cpu: 100m
          limits:
            cpu: 100m
